import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <Image src="https://i2.wp.com/3.bp.blogspot.com/-4vW18oUZK5o/W5GOdN9GW5I/AAAAAAAAajk/go1e17ybyKMfJY3yvPfQw_7LscATjqc8QCLcBGAs/s1600/victoria%2Bmemorial%252C%2Bkolkata-04.JPG?ssl=1" 
     alt="Picture of the author"
     height={500}
     width={700}  />
      </div>
    </div>
  )
}
